### ISSUE TITLE
Native All?

### ISSUE THREAD

**Issue by randyridge** [kleisauke/net-vips#108]
Is there a reason that a nuget -all variant isn't published?  It's a hassle copying overtop everytime I do a build... :D

**Comment by kleisauke** [comment]
The prebuilt binaries provided by NetVips for libvips and its dependencies do not include GPL-licensed or patent-encumbered software.

**Comment by randyridge** [comment]
I guess I'm unclear on the delineation since I can get the prebuilt encumbered libraries as well..

**Comment by kleisauke** [comment]
Using GPL-licensed libraries means that _your_ code must comply with the GPL when you use it. After PR https://github.com/libvips/build-win64-mxe/pull/14 (included in [v8.10.2](https://github.com/libvips/build-win64-mxe/releases/tag/v8.10.2)) the patent-encumbered dependencies have been moved to a plugin, but they can still be built optionally. 

The `-all` variant released on https://github.com/libvips/libvips/releases includes patent-encumbered HEVC-related logic as it builds libde265 (I just opened https://github.com/libvips/build-win64/issues/44 to fix this).

If you are satisfied with the GPL, and you want to take the patent risk, you are free to use the `-all` variant.

**Comment by randyridge** [comment]
Say for instance you want to add an avif benchmark in Netvips.Benchmarks, how would you work around?

**Comment by kleisauke** [comment]
AVIF still has patents, but they are royalty-free and the alliance of tech giants behind it will [defend it](http://aomedia.org/press%20releases/the-alliance-for-open-media-statement/) from patent troll's lawsuits.

**Comment by randyridge** [comment]
Sorry I was being explicit, in my case I have a benchmark .net benchmark that does:
``` csharp
ImagePipeline
  .FromFile("input.jpg")
  .Resize(Width, Height)
  .ToFile("output.avif");
```

While I can reference Netvips.Native and manually copy dlls to the appropriate native folder, benchmark .net does its own compile and at runtime fails the avif benchmark... To the best of my knowledge I don't think I can hook benchmark .net to copy the native/encumbered libraries as a post build step...

**Comment by randyridge** [comment]
Honestly I'm getting confused now :(  I took the same benchmark and ran on my primary work machine vs my home machine, the work machine supports AVX2 and both used 
```
<PackageReference Include="NetVips" Version="1.2.4.235-develop" />
<PackageReference Include="NetVips.Native" Version="8.10.5.1" /
```
without avx2 machine 1 fails, with avx2 machine 2 succeeds

**Comment by kleisauke** [comment]
> To the best of my knowledge I don't think I can hook benchmark .net to copy the native/encumbered libraries as a post build step

Is this for Windows? If so, you could try to add the `bin` folder of the libvips Windows build to your `PATH` environment variable (see [the standard DLL search order](https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order#standard-search-order-for-desktop-applications)). On Linux and macOS it is much easier to use a globally-installed libvips.

Alternatively, see https://github.com/kleisauke/net-vips/issues/15#issuecomment-417629143 for a detailed instruction to set the libvips binary directory at runtime (i.e. in a separate directory without changing any environment variables). 

> If there were available a NetVips.Native.All.Stay.Away nuget I don't think I'd have any issues.. Of course, I could package it on my own, it just seems like an extraneous step.

This is not going to happen due to the above reasons. You are free to build, package and distribute it yourself, but if you are using a library that is released under the GPL license, then the entire project needs to be available under a GPL-compatible open-source license.

If your goal is to distribute the `-all` variant via NuGet, make sure that the package is private/unlisted and does not contain any references to NetVips. You can also host your own NuGet feed, or using a local NuGet package feed, which might be more appropriate. See for details: https://docs.microsoft.com/en-us/nuget/hosting-packages/overview

> ```
> <PackageReference Include="NetVips" Version="1.2.4.235-develop" />
> <PackageReference Include="NetVips.Native" Version="8.10.5.1" /
> ```
> 
> without avx2 machine 1 fails, with avx2 machine 2 succeeds

Was `NetVips.Native` installed via the nightly packing (`https://ci.appveyor.com/nuget/net-vips`)? If so, it was probably using a cached version of the native binaries. I fixed this with commit https://github.com/kleisauke/net-vips/commit/b7ad9aab483da5ddbb63c2b41756c6b666da5eb0.
