### ISSUE TITLE
upgrade to newer libvips version

### ISSUE THREAD

**Issue by HolyOne** [kleisauke/net-vips#111]
Hello, I tried to save as GIF but could not achieve it because this library was looking for libvips 4.2

I see that newer version of libvips can save in gif format but it seems in .net library i am limited to an older version.

**Comment by HolyOne** [comment]
By the way I use NetVips.Native  package for adding binaries to my project. but as I see I have no other option since the project supports 4.2 version

**Comment by kleisauke** [comment]
What did you mean with `4.2`? I think you meant `42` which is libtool ABI number visible in the filename of the libvips binaries. These version does not not correspond to the major / minor / patch version but means that the ABI is stabilized since libvips 8.0.

See https://github.com/kleisauke/net-vips/issues/108 for the reason why ImageMagick is not included in the prebuilt libvips binaries released on NuGet.

**Comment by kleisauke** [comment]
Hope this helped, please re-open if questions remain.
