### ISSUE TITLE
Use enumerations for ease of use

### ISSUE THREAD

**Issue by HolyOne** [kleisauke/net-vips#112]
Hello,
I see that i have to input some string values as parameters which makes me go search a lot of documentation.
for example

`
 NetVips.Image.Thumbnail(path, w, h, crop: "attention"))
`
Why not use 

`
public enum CropParameters
{ 
attention ,  someotheroption, ...
}
`

**Comment by kleisauke** [comment]
The reason for this was that passing strings was more dynamic (and maintainable), since there is no need to release a new NetVips version every time a new enumeration is added within libvips.

But I agree, I think using enumerations instead of strings makes more sense. I had an attempt to implement this, see commit https://github.com/kleisauke/net-vips/commit/19486a770bc031fcc83d15a9d710ef0a1018cfca on the [`enum`](https://github.com/kleisauke/net-vips/tree/enum) branch. If you want to test this, you can use the nightly version of NetVips. Add the `https://ci.appveyor.com/nuget/net-vips` feed in the `<packageSources>` section of your `NuGet.config`:
```xml
<packageSources>
  <add key="netvips-nightly" value="https://ci.appveyor.com/nuget/net-vips" />
</packageSources>
```

And update NetVips to 2.0.0 (build number 239 - prerelease). I'll try to release this as v2.0.0 soon.

**Comment by kleisauke** [comment]
[NetVips v2.0.0](https://www.nuget.org/packages/NetVips/2.0.0) is now available. Thanks for reporting this!
