### ISSUE TITLE
System.DllNotFoundException: 'Unable to load DLL 'libvips-42.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)'

### ISSUE THREAD

**Issue by PavKmiec** [kleisauke/net-vips#136]
Hi,

I could use some help setting up Net-Vips on Windows (Visual Studio) for .Net Framework 4.6.1.
I have tried Net-Vips before with .NET 5 on Linux and it worked flawlesly. 

When I install `NetVips 2.0.1` (.NET bindings for libvips) and then `NetVips.Native 8.11.3` from NuGet and run my test application it throws: 

`System.DllNotFoundException: 'Unable to load DLL 'libvips-42.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)'`

I have tried to install the NuGet packages in various orders, also to try install the x86 and x64 separately but nothing helped.

I'd appreciate some advice on making this work. Thanks.

**Comment by hey-red** [comment]
I'm create console app for .NET 4.6.1

```C#
namespace NetVipsTest
{
    internal class Program
    {
        private static void Main(string[] args)
        {
            if (ModuleInitializer.VipsInitialized)
            {
                Console.WriteLine($"Inited libvips {NetVips.NetVips.Version(0)}.{NetVips.NetVips.Version(1)}.{NetVips.NetVips.Version(2)}");
            }
            else
            {
                Console.WriteLine(ModuleInitializer.Exception.Message);
            }
            Console.ReadLine();
        }
    }
}
```

and it's works fine. All required dlls copied into destination directory.

![example](https://user-images.githubusercontent.com/1738743/131215042-3befd972-eeb3-40d8-96f4-da4ad6e09871.png)

**Comment by kleisauke** [comment]
I could reproduce this when building with .NET Framework v4.5 and v4.6.1. It looks like this `<Link Condition=...` XML-element in the `.targets` file will no longer default to `%(Filename)%(Extension)` when the `LibvipsOutputBase` property is not set.
https://github.com/kleisauke/net-vips/blob/7c7559475fb611101fcac909e606cab40aa90988/build/native/targets/NetVips.Native.win-x64.targets#L6

This prevents the native DLL files from being copied to the output directory when building with .NET Framework. On .NET Core, this is not needed at all, so that should work fine, as you've noticed.

The strange thing about this is that it did work in the past, so I think a recent MSBuild or NuGet upgrade broke this. FWIW, I couldn't reproduce this using the example project file (which should do the same thing as the specific `.targets` file).
<details>
  <summary>ConsoleApp1.csproj</summary>

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net461</TargetFramework>
    <!-- <LibvipsOutputBase>x64</LibvipsOutputBase> -->
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NetVips.Native.win-x64" Version="8.11.3" GeneratePathProperty="true" IncludeAssets="none" />
  </ItemGroup>

  <ItemGroup>
    <None Include="$(PkgNetVips_Native_win-x64)\runtimes\win-x64\native\*">
      <Link Condition="'$(LibvipsOutputBase)' != ''">$(LibvipsOutputBase)\%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
```
</details>

Fortunately, there's a way to workaround this by setting `LibvipsOutputBase` to `.` in your project file. For example:
```xml
<PropertyGroup>
  <LibvipsOutputBase>.</LibvipsOutputBase>
</PropertyGroup>
```

Commit https://github.com/kleisauke/net-vips/commit/9fba9ccf67243e7ba9af0f4b0abccea794ac40f5 should also fix this. If you want to test this, you can use the nightly version of NetVips.Native. Add the `https://ci.appveyor.com/nuget/net-vips` feed in the `<packageSources>` section of your `NuGet.config`:
```xml
<packageSources>
  <add key="netvips-nightly" value="https://ci.appveyor.com/nuget/net-vips" />
</packageSources>
```

And use NetVips.Native v8.11.3 from there (make sure you've cleared your NuGet cache, since it has the same version number). I'll make a new release soon.

**Comment by PavKmiec** [comment]
@kleisauke thank you for fast reply and comprehensive instructions on how to fix this. I will try this on Monday and will report back. Many thanks.

**Comment by kleisauke** [comment]
[NetVips.Native v8.11.3.1](https://www.nuget.org/packages/NetVips.Native/8.11.3.1) is now available with this fix included. Thanks for reporting this!
