### ISSUE TITLE
NullReferenceException or ExecutionEngineException during Tiffsave when reporting progress

### ISSUE THREAD

**Issue by LionelArn2** [kleisauke/net-vips#141]
Hey there,

First of all, thanks for your work on libvips. Its performance is quite remarkable and it has been most useful :)

I'm running into a recurrent issue when using Tiffsave repeatedly. I created a very simplified version of my code to reproduce the crash:
       
```
Random rand = new();
while (true)
{
    NetVips.Image imageSource = NetVips.Image.Tiffload(@"path\to\image.tiff", n: -1);

    imageSource.SetProgress(new Progress<int>());

    imageSource.Tiffsave(@"path\to\output\" + rand.Next().ToString() + ".tiff");
}
```

During the execution, the following exception gets thrown during Tiffsave:
`System.NullReferenceException: 'Object reference not set to an instance of an object.'`
An `ExecutionEngineException` also gets thrown sometimes instead of the `NullReferenceException`.

These exceptions never occur at the first iteration of the `while` loop, always at the 2nd or later. They also do not occur if I do not use `SetProgress`

The tiff image I've been using for this test is of dimensions 25000x5000 with page height 5000 (ushort).

This post https://github.com/kleisauke/net-vips/issues/31 mentions a similar issue with codes very similar to the one above. I tried the different codes from this post and did not have any issue, however replacing `Dzsave` with `Tiffsave` suffices to create the crash in my case.

Am I doing something wrong?

**Comment by kleisauke** [comment]
Hi @LionelArn2,

You're not doing anything wrong. It looks like a bug, I could reproduce this with:
```csharp
//Cache.Max = 0;

for (int i = 0; i < 1000; i++)
{
    using Image image = Image.Tiffload(@"Images\sample.tif");
    image.SetProgress(new Progress<int>());
    image.Tiffsave($"{i}.tiff");
}
```

Uncommenting `Cache.Max = 0` makes it work without problems. The reason is that libvips reuses the image from the operation cache after subsequent use, but the connected [`Enums.Signals.Eval`](https://kleisauke.github.io/net-vips/api/NetVips.Enums.Signals.html#NetVips_Enums_Signals_Eval) callback handler is released too early causing `ExecutionEngineException` (or `NullReferenceException`) to be thrown:
```
Process terminated. A callback was made on a garbage collected delegate of type 'NetVips!NetVips.Internal.VipsImage+EvalSignal::Invoke'.
```

Commit https://github.com/kleisauke/net-vips/commit/8682c66f69c64c7b5feae49f8dc5169f75f193ca should fix this. If you want to test this, you can use the nightly version of NetVips. Add the `https://ci.appveyor.com/nuget/net-vips` feed in the `<packageSources>` section of your `NuGet.config`:
```xml
<packageSources>
  <add key="netvips-nightly" value="https://ci.appveyor.com/nuget/net-vips" />
</packageSources>
```

And update NetVips to 2.0.1 (build number 291 - prerelease). I'll make a new release soon.

**Comment by LionelArn2** [comment]
That's great, thanks for your help and the prompt response!

**Comment by kleisauke** [comment]
[NetVips v2.1.0](https://www.nuget.org/packages/NetVips/2.1.0) is now available.
