### ISSUE TITLE
Dynamic libvips path ?

### ISSUE THREAD

**Issue by gjactat** [kleisauke/net-vips#15]
Hello,
We have several types of C# processes that might use NetVips (and therefore, libvips). Some of them are 64bits and some of them are 32bits, some are web services, some are windows services.

To deal with that, I try to add the appropriate libvips path to the PATH environement variable *at run time* and at the process level (EnvironmentVariableTarget), depending of the current process architecure.

The problem is that ModuleInitializer's "Initialize" method is called way before any other code... So it's hard to patch the path variable without modifying NetVips code itself.

Do you a know a proper way to deal with this kind of dynamic libvips path ?

Thanks for your attention,
Guillaume

**Comment by kleisauke** [comment]
You could use an own module initializer in your program (to ensure that your own program is initialized first). Install the [ModuleInit.Fody](https://www.nuget.org/packages/ModuleInit.Fody/) NuGet package, add a new file named `FodyWeavers.xml` file at the project level with the following content:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<Weavers VerifyAssembly="true"
         VerifyIgnoreCodes="0x80131869,0x80131252">
         <!-- ignore 0x80131869 and 0x80131252 since it throws on netstandard -->
  <ModuleInit/>
</Weavers>
```

Then add a `ModuleInitializer` class, which will P/Invoke `SetDllDirectory` with the location of libvips, depending on the architecture where the C# process is running on:
```csharp
using System;
using System.IO;
using System.Runtime.InteropServices;

namespace ConsoleApp
{
    /// <summary>
    /// Used by the ModuleInit. All code inside the Initialize method is ran as soon as the assembly is loaded.
    /// </summary>
    public static class ModuleInitializer
    {
        /// <summary>
        /// Initializes the module.
        /// </summary>
        public static void Initialize()
        {
            Console.WriteLine("Loading libvips " + (Environment.Is64BitOperatingSystem ? "x64" : "x86") + "-binary.");
            SetDllDirectory(Path.GetFullPath(Environment.Is64BitOperatingSystem
                ? @"C:\vips-dev-8.7-w64\bin"
                : @"C:\vips-dev-8.7-w32\bin"));
        }

        [DllImport("kernel32.dll", CharSet = CharSet.Auto, SetLastError = true)]
        [return: MarshalAs(UnmanagedType.Bool)]
        public static extern bool SetDllDirectory(string lpPathName);
    }
}
```
(See [here](https://stackoverflow.com/a/8861895/1480019) for more information about `SetDllDirectory`).

Also make sure that NetVips doesn't use the bundled libvips:
```xml
<PropertyGroup>
  <UseGlobalLibvips>true</UseGlobalLibvips>
</PropertyGroup>
````

If you could not use an own module initializer in your program, then you'll need to build NetVips with the module initializer disabled and call `NetVips.Base.VipsInit()` by yourself. I do not intend to add a check for an environment variable to conditional disable the module initializer because for performance reasons and to not break someone's program.

**Comment by gjactat** [comment]
Thanks for your quick answer !
The change i've made to NetVips seems close to to your second solution.

**Comment by kleisauke** [comment]
This is much easier now with the [`ResolvingUnmanagedDll` event](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.loader.assemblyloadcontext.resolvingunmanageddll).

```csharp
using System.Runtime.InteropServices;
using System.Runtime.Loader;
using NetVips;

AssemblyLoadContext.Default.ResolvingUnmanagedDll += (_, libName) =>
    NativeLibrary.Load($"C:/vips-prefix/bin/{libName}");

// Try to init again in case the ModuleInitializer fails.
if (!ModuleInitializer.VipsInitialized)
{
    ModuleInitializer.Initialize();
}

using var image = Image.Text("Hello <i>World!</i>", dpi: 300);
image.WriteToFile("hello-world.png");
```
