### ISSUE TITLE
svg to tiff, some elements are lost

### ISSUE THREAD

**Issue by llibetter** [kleisauke/net-vips#158]
https://design.blob.core.chinacloudapi.cn/test/XI_0c4a60de18c24ff08fc3552473fd09ea.svg
this is my svg file.

`
       
       private const double DPIRESCOEF = 25.4;

        public static double GetResFromDpi(double dpi)
        {
            return dpi / DPIRESCOEF;
        }
        static void Svg2Tiff()
        {
            var stream = DownloadStreamAsync(
                "https://design.blob.core.chinacloudapi.cn/test/XI_0c4a60de18c24ff08fc3552473fd09ea.svg");
            Image image;
            var scale = 7;
            var quality = 95;
            var dpi = 300;
            image = Image.SvgloadStream(stream, scale: scale, access: Enums.Access.Sequential);

            var res = GetResFromDpi(dpi);
            var bytes = image.TiffsaveBuffer(compression: Enums.ForeignTiffCompression.Lzw, q: quality, xres: res, yres: res);
            
            var resStream = new MemoryStream(bytes);
            image.Dispose();
            StreamToFile(resStream,"c:\\20220120.tiff");
        }
`

thanks!

**Comment by llibetter** [comment]
![image](https://user-images.githubusercontent.com/44372726/150356510-d44ae5f0-d03f-46cd-896a-b3c448ae1df6.png)
this element will be lost

**Comment by kleisauke** [comment]
Hi @llibetter,

Sorry for the delay. I think this issue is a result of cairo's (the render library used by librsvg) 16.16 fixed point coordinate limit, since the produced image is 7168x7168 pixels. librsvg has to walk through the tree with a cairo bounding box to find the visible parts of the drawing. These calculations may overflow even if the viewport is within the 32k limit, causing parts to be incorrectly rendered or not rendered at all.

We've been looking at other SVG rendering libraries (see https://github.com/libvips/libvips/discussions/2048), but no decision has yet been made on how to improve it.

**Comment by kleisauke** [comment]
I hope this information helped. Please feel free to re-open if questions remain.
