### ISSUE TITLE
Image Interpretation issue with Grey16 images for NewFromMemory() method

### ISSUE THREAD

**Issue by ratok-mk** [kleisauke/net-vips#192]
**Problem**
I need to load 16bpp images from byte arrays and save them as an image. 
_Example:_ 
Image netVipsImage = Image.NewFromMemory(
            image.Data, (int)image.Width.Value, (int)image.Height.Value, 1, Enums.BandFormat.Ushort);
It returns with the interpretation set to 'b-w' instead of the expected 'Grey16'. 

When I use the method NewFromFile() a standard 16-bit image the interpretation is set correctly to "Grey16".
_Example:_
Image image = Image.NewFromFile(filePath, access: Enums.Access.Sequential)

**Expectation:**
So I would expect, that NewFromMemory() can either detect "Grey16" automatically or has the option to force the interpretation.

**Current Workaround**
I saw it can be workarounded by using netVipsImage.Copy(interpretation: Enums.Interpretation.Grey16);
So I expect some performance loss for the extra copy operation?

**Comment by kleisauke** [comment]
Hi @ratok-mk,

[`Image.NewFromMemory()`](https://www.libvips.org/API/current/VipsImage.html#vips-image-new-from-memory) always sets the interpretation to `b-w` (`Enums.Interpretation.Bw`) for single-band images. For 3-band images it'll set the interpretation to `srgb` (`Enums.Interpretation.Srgb`) and otherwise it'll use the generic `multiband` interpretation (`Enums.Interpretation.Multiband`).

I'm not sure if libvips should use a different interpretation depending on the pixel format in this function, as it would break compatibility if we introduced such a change.

> So I expect some performance loss for the extra copy operation?

[`image.Copy()`](https://kleisauke.github.io/net-vips/api/NetVips.Image.html#NetVips_Image_Copy_) would end-up calling [`vips_copy()`](https://www.libvips.org/API/current/libvips-conversion.html#vips-copy), which only copies pointers, so this operation is instant, even for very large images.

**Comment by ratok-mk** [comment]
Thanks for the insides, I just got confused by the name copy. So that closes the issue.
