### ISSUE TITLE
Regression in 2.4.0: Images being saved in black & white

### ISSUE THREAD

**Issue by majora2007** [kleisauke/net-vips#226]
In version 2.4.0, some images are not correctly creating a Thumbnail. This was working with this:

```
    <PackageReference Include="NetVips" Version="2.3.1" />
    <PackageReference Include="NetVips.Native" Version="8.14.5" />
```

See:
![295280149-3af5fd6d-9d29-472b-901f-fe297f4f1d94](https://github.com/kleisauke/net-vips/assets/735851/24e377c7-936a-47cb-89dc-0f4bedf1076b)
From:
![295280155-8b7f73ba-0164-4698-937e-0a3a8e2920da](https://github.com/kleisauke/net-vips/assets/735851/0aa266fa-cbcf-45aa-8cf7-ceae2791456a)

Relevant Code:
```
using var thumbnail = Image.Thumbnail(sourceFile, dims.Width, height: dims.Height, size: Enums.Size.Force);
thumbnail.WriteToFile(...);
```

**Comment by kleisauke** [comment]
This is due to the use of a CPU that doesn't support SSE4, possibly QEMU-emulated, with somewhat non-standard flags.

There's an upstream fix to support this configuration at https://github.com/libvips/libvips/pull/3763 that has been included in libvips v8.15.1. I'll try to incorporate that in `NetVips.Native` somewhere this weekend.

You can workaround it for now with one of the following:
- ensuring the hypervisor allows the use of CPU intrinsics such as SSE4
- setting the `VIPS_NOVECTOR` environment variable before importing `NetVips`
- using `NetVips.Vector = false` to switch off the use of SIMD.

https://kleisauke.github.io/net-vips/api/NetVips.NetVips.html#NetVips_NetVips_Vector

**Comment by majora2007** [comment]
Looks like the hypervisor fix worked. It always comes down to SSE4.

If I turn off vectorization, will this allow CPUs that don't support SSE4 work with this library, just slower?

**Comment by kleisauke** [comment]
[NetVips.Native v8.15.1](https://www.nuget.org/packages/NetVips.Native/8.15.1) is now available.

> If I turn off vectorization, will this allow CPUs that don't support SSE4 work with this library, just slower?

The prebuilt Linux x64 binaires provided by NetVips require a CPU that supports SSE4.2. Disabling SIMD support in libvips doesn't eliminate this necessity, since the compiler might still use SSE4.2 instructions as part of auto-vectorization.

**Comment by majora2007** [comment]
Ahh okay. Thanks!
