### ISSUE TITLE
Saving from PDF file to TIFF/JPEG crashes silently

### ISSUE THREAD

**Issue by goarsna** [kleisauke/net-vips#23]
Hi,

I've got a problem saving a loaded PDF file to a JPEG or TIFF file. Unfortunately the error seems to occur only in some special cases with vector PDF files.

### The files:
In my case I've got a set of vector PDF files all created by Ghostscript 9.14 using the PDF24 PDF creator. All PDF files are in the PDF 1.4 format. One file can be saved as a JPEG/TIFF file, the others fail.
Unfortunately at the moment I'm not able to provide an example PDF file where this error occurs due to reasons of privacy protection...

### My problem:
The following sample code crashes silently at calling **WriteToFile()**.

`
var vipsImage = NetVips.Image.NewFromFile("test_input.pdf");
vipsImage.WriteToFile("test_output.jpg");
`

### Details:
Including the NetVips project (master branch) directly into my C# project and debugging through each single step, reveals that the call of `VipsOperation.VipsCacheOperationBuild(op);` in **Operation.cs, line 265** crashes silently with `op` being an Operation created by the call of `NewFromName(operationName);` in **Operation.cs, line 187** where `operationName` is **VipsForeignSaveJpegFile**.
As mentioned in the beginning this also fails with an output filename ending with **.tiff** and therefore **VipsForeignSaveTiffFile** as `operationName`.

### Question:
Unfortunately without an example file it may be hard to reproduce this error. But do you have any clue what could cause this error?

### Edit:
I just tried to save the PDF file to the vips format by calling `WriteToFile("test_vips.v");`. This also leads to the error. Therefore i suppose the output format doesn't matter...

Thanks in advance for any help. :)

**Comment by kleisauke** [comment]
Assuming you use Windows; I suspect this could be a DLL load issue. I couldn't reproduce this with NetVips 1.0.5 and:
- vips-dev-w64-all-8.7.1.zip from the [libvips repo](https://github.com/libvips/libvips/releases/tag/v8.7.1).
- vips-dev-w64-all-8.7.1.zip from the [build-win64-mxe repo](https://github.com/libvips/build-win64-mxe/releases/tag/v8.7.1).
- vips-dev-w64-all-8.7.0.zip from the [build-win64-mxe repo](https://github.com/libvips/build-win64-mxe/releases/tag/v8.7.0).

I did some tests with the following example PDF files:
https://github.com/kleisauke/net-vips/blob/master/tests/NetVips.Tests/TestData/ISO_12233-reschart.pdf
https://gorhamprinting.com/diy-book-printing/PDFS/VectorRaster.pdf

You could also try to test with `vips.exe`, and see if this is reproducible:
```bash
vips.exe copy ISO_12233-reschart.pdf test.tiff
vips.exe copy ISO_12233-reschart.pdf test.jpg
```

Tips to solve DLL load issues:
- Try to reorder your PATH environment variable so that the `vips` bin directory (for e.g. `C:\vips-dev-8.7\bin`) is included first.
- [`Poppler`](https://poppler.freedesktop.org/) (the PDF loader that libvips uses) depends on [`Cairo`](https://www.cairographics.org/) for vector graphics. Check if your PC contains multiple files named `libcairo-2.dll`.
- Also search for `libpoppler-82.dll`, `libpoppler-80.dll` or `libpoppler-63.dll` depending on which libvips binary distribution you use.

By the way, which libvips distribution did you use?

**Comment by goarsna** [comment]
Hi and thanks for your response,

At first I have to apologize... I forgot to mention that I already tried to convert the PDF file from command line and that this works.

For testing (via command line and NetVips) I used a global installation of libvips. Two different distributions from the official libvips repo have been tested without success: `vips-dev-w64-all-8.6.5.zip` and `vips-dev-w64-all-8.7.1.zip`

First I tested the conversion with `libvips 8.6.5`. Then I removed the `libvips 8.6.5` installation from the system path and added the `libvips 8.7.1` installation. Again no success.


Today I tried to convert the PDF file with the two **MXE builds of libvips** provided by you.
With those two the conversion of the PDF file **works as expected** (both, via command line and NetVips).

May be the update of `libcairo-2.dll` oder `libpoppler-63.dll` to `libpoppler-82.dll` fixed the issue.

Are there any other changes between libvips from the official libvips repo and the libvips MXE builds, that could have affected the PDF conversion?

Thanks for your help and the great work.

**Comment by kleisauke** [comment]
My apologies for the slow reply; I was on holidays and busy with my internship.

The binaries from the main libvips repo still dependent on older versions for PDF rendering:
- Poppler 0.46.0 (released on July 25, 2016 - which is more than 2 years ago).
- Cairo 1.15.12 (release on April 11, 2018).

Since May of this year, many security/leak/crash issues have been found (Poppler is continuous fuzzed by [OSS-Fuzz](https://github.com/google/oss-fuzz)), so perhaps this problem has already been solved. 

The advantage of the `build-win64-mxe` distribution is that all dependencies are updated to the latest version (where possible), so it'll reduce crashes and the attack surface. Hopefully this distribution will be incorporated in the official libvips binaries (see libvips/build-win64#22).

The odd thing is that you cannot reproduce this from the command line with the official libvips binaries, so maybe this is a problem with NetVips. I've a couple of questions:
1. Are you sure that the `UseGlobalLibvips` property is to `true`? There may be a possibility that the bundled binaries of NetVips may conflict with the globally installed binaries.
2. Could you reproduce the crash with example PDF files from https://github.com/kleisauke/net-vips/issues/23#issuecomment-443769954? If not, can you provide some details of the PDF that causes this crash? (for e.g. included fonts because Cairo recently fixed a crash with `Microsoft's Segoe UI Emoji Regular` font).

Is there any chance you could email the PDF that causes this crash privately to me at info@kleisauke.nl so I can attempt to reproduce? I could sign a mutual NDA enforcing that I only use your PDF privately and with the sole goal of improving NetVips, if that makes you feel more comfortable.

**Comment by goarsna** [comment]
Hi,
sorry that my reply took that long. I wanted to reply days ago. But due to a lot of work, I simply forgot to write... :(

To answer your questions:

1. Yes, definitely. `UseGlobalLibVips` is set to `true` and I verified by checking the files in the build directory.
2. I tried to reproduce the error with the example PDF files. But none of them showed the error.

Unfortunately also with a signed NDA, I won't be allowed to provide one of those erroneous PDF files due to data privacy.
Currently I'm keeping my eyes open for a PDF file I can provide to you and which shows the same erroneous behavior. As soon as I've found one I'll provide it to you.

For me up to now it seems like the problem was caused by the outdated versions of `Cairo` and `Poppler`.
We now switched to use the `build-win64-mxe` distribution of `libvips 8.7.1`, as we didn't encounter any similar problem in our testing phase with this build.

Thanks a lot for your help!
