### ISSUE TITLE
Dz different folder structure

### ISSUE THREAD

**Issue by feelgood-interface** [kleisauke/net-vips#235]
Since the change of the dzsave library (https://github.com/libvips/libvips/issues/3354) the folder structure is different.

1. Previously when saving as a ZIP the folder structure was:
`basename/basename_files/...`
Now it is:
`basename_files/...`
Will this now be the default folder structure?
2. The modified timestamp of the files is incorrectly set to`1980-01-01 00:00`, but this is probably related to the `libarchive` library.

**Comment by kleisauke** [comment]
Hi @feelgood-interface,

I believe the previous folder structure was necessary because libgsf required a parent directory for writing, see e.g. PR:
https://github.com/libvips/libvips/pull/465

Which was more of a workaround, I believe we have now decided to use this "new" folder structure as the default. (/cc @jcupitt)

As for point 2, this can be useful to create deterministic ZIP files, see for example the test script in PR:
https://github.com/libvips/libvips/pull/3687

**Comment by jcupitt** [comment]
Hello Kleis and @feelgood-interface, yes, the previous folder structure was forced on us and the new structure is the one we plan to stick to if we possibly can.

**Comment by kleisauke** [comment]
I hope this information helped. Please feel free to re-open if questions remain.
