### ISSUE TITLE
NetVips Image.WriteToBuffer (and possibly others) Not Working with Windows ActiveDirectory Impersonation

### ISSUE THREAD

**Issue by ASSET5375** [kleisauke/net-vips#239]
Hi,

I'm using **WindowsIdentity.RunImpersonated** function with the **SafeAccessTokenHandle** to impersonate another Windows AD User. Inside, I'm using NetVips **WriteToBuffer** on an NetVips.Image generated using NewFromFile(FilePath) to get the Byte Array representation. This FilePath is in a Folder that has been denied all Read/Write permissions to everyone **except** the impersonated AD User.

WriteToBuffer errors out with the following:

unable to call VipsForeignSaveSpngTarget
\\Part5689\Data\TestDenied\image1.png: unable to open for read
windows error: The data is invalid.

\\Part5689\Data\TestDenied\image1.png: unable to open for read
windows error: The data is invalid.

pngload: stream error

**Comment by kleisauke** [comment]
Could you reproduce this when using `Image.NewFromBuffer(File.ReadAllBytes(Filename))` instead of `NewFromFile(Filename)`? I suspect the error isn't in `WriteToBuffer()`, as the error message points to an issue with `pngload`.

Note that libvips is demand-driven, meaning all processing is deferred until the final write to file, buffer, or memory.

**Comment by ASSET5375** [comment]
thanks @kleisauke that worked. Not sure why NewFromFile isn't working. I guess AD impersonation only works on direct IO calls?
