### ISSUE TITLE
Question: Best way to load and save files from a buffer when file type is not known

### ISSUE THREAD

**Issue by avin-kavish** [kleisauke/net-vips#37]
I'm loading images from the `IFormFile` container. I'm not sure what the best way is to find the image type so that I can save the images in the original format they were uploaded in. `IFormFile.ContentType`  might not be reliable. I'm aware that libvips sniffs the first few bytes when loading a file from disk, is there a way to replicate that behaviour in this library? Perhaps to sniff from the intermediary buffer I'm using to load the image.

**Comment by kleisauke** [comment]
libvips has two useful functions to quickly identify the image type:
- [`vips_foreign_find_load`](https://libvips.github.io/libvips/API/current/VipsForeignSave.html#vips-foreign-find-load)
- [`vips_foreign_find_load_buffer`](https://libvips.github.io/libvips/API/current/VipsForeignSave.html#vips-foreign-find-load-buffer)

I just made these functions available in NetVips with commit https://github.com/kleisauke/net-vips/commit/3fffefc9c2aab64fbc3928d629823595ab333335.

Note that these functions will not detect truncated images, it just performs some basic verification of image metadata. For example, reading a buffer with `GIF89a` will result in `VipsForeignLoadGifBuffer`.

If you also want to detect broken images, you can use this:
https://github.com/kleisauke/net-vips/blob/3fffefc9c2aab64fbc3928d629823595ab333335/samples/NetVips.Samples/Samples/IdentifyExtension.cs#L40-L63

**Comment by avin-kavish** [comment]
Thanks for the prompt attention, when will this ship on nuget?

**Comment by kleisauke** [comment]
I'm a bit busy with college and other side projects these days, but I hope to release NetVips 1.1.0 a few days after libvips 8.8.1 is released (libvips 8.8.1 will be released within a few days). Version 1.1.0 is more or less ready to be shipped (:shipit:). NetVips.Native takes most of the time, because I try to keep the [dependencies](https://github.com/libvips/build-win64-mxe#libvips-web-dependencies) up-to-date (where possible).

If you want to test this earlier, you can use the nightly version of NetVips. Add the `https://ci.appveyor.com/nuget/net-vips` feed in the `<packageSources>` section of your `NuGet.config`:
```xml
<packageSources>
  <add key="netvips-nightly" value="https://ci.appveyor.com/nuget/net-vips" />
</packageSources>
```

And update NetVips to version 1.1.0.140-develop.

**Comment by kleisauke** [comment]
NetVips 1.1.0-rc3 is released on NuGet. If there's nothing reported for a week, this will become 1.1.0 final.

**Comment by avin-kavish** [comment]
`FindLoadBuffer` seems stable so far. Closing as resolved.

**Comment by kleisauke** [comment]
NetVips v1.1.0 is now available.
