### ISSUE TITLE
Better way to write native files

### ISSUE THREAD

**Issue by Gigas002** [kleisauke/net-vips#51]
Hello.
I'm using NetVips along with others projects on Linux. After building the project with **NetVips.Native** package, it writes Linux dependencies in "runtimes/linux-x64/native" directory.
However, another [library](https://www.nuget.org/packages/MaxRev.Gdal.LinuxRuntime.Minimal/) writes its dependencies the same way and overrides some files. Because of that, NetVips in my application doesn't work, throwing the exception:

```text
Message [string]:"Unable to load shared library 'libvips.so.42' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibvips.so.42: cannot open shared object file: No such file or directory"
```

Probably the native binaries should be written the other way to avoid these conflicts?

**Comment by kleisauke** [comment]
It looks like the `libz.so.1` (zlib as shared library) from that package conflicts with our zlib (with the same filename). sharp also had these issues in the past (see https://github.com/lovell/sharp/issues/843 and https://github.com/lovell/sharp/issues/892), this could be resolved by setting the `LD_PRELOAD` environment variable or by ensuring that the zlib versions are the same among NPM packages.

The `LD_PRELOAD` trick does not work here since the shared library of the `NetVips.Native.linux-x64` is being replaced. It would also be difficult to ensure that the zlib versions is the same among all NuGet packages.

An alternative way to resolve this is by building a statically linked library for Linux (just like the Windows builds). I tried this (as an experiment) with commit https://github.com/kleisauke/libvips-packaging/commit/982f59e7d2f5a2de516aa78b6584eda8aeed4baf and released it with [NetVips.Native v8.9.0-rc4](https://www.nuget.org/packages/NetVips.Native/8.9.0-rc4) (pre-release). 

Let me know if this works for you!

**Comment by kleisauke** [comment]
Note to myself: Investigate building a statically linked library for macOS (with or without Homebrew) it may also cause problems in the future.

**Comment by Gigas002** [comment]
Thank you, I've run through some tests and **8.9.0-rc4** seems to work properly.

**Comment by kleisauke** [comment]
[NetVips.Native v8.9.1](https://www.nuget.org/packages/NetVips.Native/8.9.1) is now available. Any potential improvements for the macOS pre-compiled libvips binaries can be tracked at https://github.com/kleisauke/libvips-packaging/issues/1.
