### ISSUE TITLE
performance question .NET Binding vs command line

### ISSUE THREAD

**Issue by CanadianHusky** [kleisauke/net-vips#65]
Hello,

I have installed the latest .NET binding with `PM>Install-Package NetVips -Version 1.2.0` and execute this code

```
{
    Stopwatch sw = new Stopwatch(); sw.Start();
    string input = @"c:\temp\input.jpg";
    NetVips.Image vipsimg = Image.NewFromFile(input, true);
    vipsimg = vipsimg.Rot90;
    vipsimg.WriteToFile(@"C:\temp\output.jpg");
    vipsimg.Dispose();
    sw.Stop();
    MsgBox("Done " + sw.ElapsedMilliseconds);
}
```

Result = **1400 ms** (average after 5 runs to eliminate disc caching)

I have installed the command line binary from 
`https://github.com/libvips/libvips/releases/vips-dev-w64-web-8.9.1.zip'
 and execute this command line

` vips rot "C:\temp\input.jpg" "c:\temp\output.jpg" d90`

Result after 5 runs = **6400 ms**

Can anyone explain this behaviour, isnt the .NET binding using the same libvips core ?

PS: 
GraphicsMagick does the same rotation with
`gm time convert -rotate 90 "C:\temp\input.jpg" "C:\temp\output.jpg"`

in **5700 ms**

There is no library that I tested that has the performance of NetVips. Brilliant work!
The .NET Binding is frighteningly fast, but to understand what is happening behind the scenes, is its because the .NET Binding uses a single DLL that is linked ( libvips-42.dll ) whereas the command line vesion has 38 DLLs that it needs to find and load frmo the file system ?
Antivirus is disabled and there are no other significant processes running on the PC. I repeated the test across a timespan of 30 minutes and can recreate the same results anytime.

The input file is 24bit RGB, 12742x7204 pixel size and 9321kb large.

thank you

**Comment by CanadianHusky** [comment]
I figured it out myself...

the 'true' parameter while loading, loads everything into memory and not over the temp/filesystem
NetVips.Image vipsimg = Image.NewFromFile(input, true);
settings the second parameter to false creates comparable result to the libvips command line

where can I find some usage examples how the VOptions parameter is used ?

**Comment by kleisauke** [comment]
Indeed, forcing the entire image from memory will be a lot faster than using a temporary disc file.

>where can I find some usage examples how the VOptions parameter is used ?

The full set of options available (and that can be specified in `VOption`) depend upon the load operation that will be executed. Try something like:
```bash
vips jpegload
```
at the command-line to see a summary of the available options for the JPEG loader. 

You can also [check the documentation of VipsForeign](https://libvips.github.io/libvips/API/current/VipsForeignSave.html) to see which options can be given. If you are sure that only JPEG images are loaded (for example), you can also call `Image.Jpegload`. Then you can simply provide the arguments instead of building a `VOption`.
