### ISSUE TITLE
BitmapConverter ToVips Skewed Output

### ISSUE THREAD

**Issue by FullSpectrumLaser** [kleisauke/net-vips#67]
Loading the following images (where the source image and BitmapData stride do not match) result
in skewed output:

[bmp examples.zip](https://github.com/kleisauke/net-vips/files/4300157/bmp.examples.zip)

**Comment by kleisauke** [comment]
I couldn't find any images tagged as `Format1bppIndexed` or `Format4bppIndexed`, so this wasn't implemented yet. 

Commit https://github.com/kleisauke/net-vips/commit/02d3597c7309476618c265f1f7491a114497c71c should fix this. Released on NuGet with [NetVips.Extensions v1.0.1](https://www.nuget.org/packages/NetVips.Extensions/1.0.1).

Thanks for reporting and providing these test images!

**Comment by kleisauke** [comment]
I tested all images from the [BMP test suite](https://github.com/jsummers/bmpsuite) and found a couple of color-related issues in the previous implementation. Fixed with commit https://github.com/kleisauke/net-vips/commit/0750347979478726faa3ae65c6ea3081b3f5a227 and released on NuGet with [NetVips.Extensions v1.0.2](https://www.nuget.org/packages/NetVips.Extensions/1.0.2).

**Comment by kleisauke** [comment]
I'll close this issue for now, please feel free to re-open if there's still a problem.
