### ISSUE TITLE
Question about adaptive contrast level adjustments

### ISSUE THREAD

**Issue by CanadianHusky** [kleisauke/net-vips#68]
Hello,
the more I use this library the more I am amazed by the speed and low memory usage.

I am trying to port the following functions from other processing libraries because they cannot handle large images (30,000x60,000 pixel range). NetVips has no problem on those and I can do basic channel operations. 

I looked at all posts (open and closed) in https://github.com/kleisauke/net-vips/issues/
and the samples in
https://github.com/kleisauke/net-vips/tree/master/samples/NetVips.Samples/Samples as well

but could not find samples for these 4 operations
Can someone please help me with the C# version to achieve the same effect for the following ?

1-contrast level and gamma adjustment
`gm convert -level 40%,1.0,85% input.jpg output.jpg`

I found VipsImage.Gamma()

2-whitepoint, blackpoint
`gm convert -white-threshold 80% input.jpg output.jpg`
`gm convert -black-threshold 80% input.jpg output.jpg`

3-local adaptive threshold 
`gm convert -lat 200x200-5% input.jpg output.jpg`

these commands and their parameters are explained here (http://www.graphicsmagick.org/GraphicsMagick.html)

and this chain of functions from IM
https://imagemagick.org/script/command-line-options.php#clahe
4-contrast limited adaptive histogram equalization, 

`>magick "input.jpg" -clahe 10x10%+32+11 -blur 6x2 -colorspace gray +dither -colors 2 -normalize "output.png"
`

I found the blur as vipsImage.Gausblur

Netvips/Libvips has so many low level functions that it seems possible to do anything you want with it. So I am sure these functions are possible for someone with enough experience on the library.

It would be nice if the samples could be expanded to cover more scenarios

Thank you in advance

**Comment by CanadianHusky** [comment]
Here are some answers I found

item 3

`    Image result = vipsimg > vipsimg.Gaussblur(sigma, minAmpl, precision: Enums.Precision.Integer) + offset;

offset : negative value
`
item 4 
-clahe replacement 
`    Image result = vipsimg.HistLocal(100,100,maxSlope)`
this runs awefully slow compared to ImageMagick

**Comment by kleisauke** [comment]
Sorry for the huge delay. I've been running out of bandwidth lately due to work on an unfinished OSS project. I'm glad you found some alternatives to *magick commands. It's always nice to hear that most libvips alternatives run faster.

> 1-contrast level and gamma adjustment
> `gm convert -level 40%,1.0,85% input.jpg output.jpg`
> 
> I found VipsImage.Gamma()

It looks like only the second parameter is [`vips_gamma`](https://libvips.github.io/libvips/API/current/libvips-conversion.html#vips-gamma) in libvips. The first and last one is the blackpoint and whitepoint below.

> 2-whitepoint, blackpoint
> `gm convert -white-threshold 80% input.jpg output.jpg`
> `gm convert -black-threshold 80% input.jpg output.jpg`

Am I right that this is resolved with https://github.com/libvips/libvips/issues/1567 and/or https://github.com/libvips/libvips/issues/59#issuecomment-599569958? Otherwise, I could take a look.

> 3-local adaptive threshold
> `gm convert -lat 200x200-5% input.jpg output.jpg`
> `Image result = vipsimg > vipsimg.Gaussblur(sigma, minAmpl, precision: Enums.Precision.Integer) + offset;`
> offset : negative value

That should work. I'm glad you managed to port the example mentioned in https://github.com/libvips/libvips/issues/1516#issuecomment-571470431. 

> item 4
> -clahe replacement
> ` Image result = vipsimg.HistLocal(100,100,maxSlope)`
> this runs awefully slow compared to ImageMagick


It looks like this performance issue should be fixed by https://github.com/libvips/libvips/commit/2b78a00cfb4720fa5e4836f81aa651c08a861c51, but I haven't test it by myself yet. /cc @jcupitt.

> It would be nice if the samples could be expanded to cover more scenarios

Indeed, the samples needs to be expanded. I'd be happy to accept a PR that adds more samples, if you're able.
