### ISSUE TITLE
Question: regarding filesize

### ISSUE THREAD

**Issue by maximilian-biolit** [kleisauke/net-vips#72]
Hello!
Im wondering why my images gets a larger file-size even though i have not done any processing on it. 
`
var im = Image.NewFromStream(stream);
`
`
var bytes = im.JpegsaveBuffer();
`
I have a jpeg that is 97kb. 
When saved through netvips it gets 147kb

**Comment by CanadianHusky** [comment]
Hello,
your sample code does not define a jpeg quality, so netvips will use its own default.
If your original file had a strong compression, lets say 25% quality factor and the netvips default is 75% your filesize would increase due to unpacking and repacking.

See https://github.com/kleisauke/net-vips/issues/35 for Jpeg filesize/compression options

**Comment by maximilian-biolit** [comment]
@CanadianHusky Thank you!
