### ISSUE TITLE
Using MozJPEG

### ISSUE THREAD

**Issue by design-revision** [kleisauke/net-vips#92]
Hello,

I was wondering if there is a way to configure `libvips`/`net-vips` to use MozJPEG (I'm using .NET Core inside Docker running Ubuntu) I searched the web, but couldn't find anything that would point me in the right direction.

Any hint would be highly appreciated!

**Comment by kleisauke** [comment]
You could try to adapt this Dockerfile to your needs:
https://github.com/jcupitt/docker-builds/tree/master/libvips-mozjpeg-ubuntu18.10

Make sure you do not install any packages which depend directly (or indirectly) on libjpeg(-turbo), as you want to use MozJPEG.

Let me know if you need any help with this.

**Comment by kleisauke** [comment]
Hope this helped, please feel free to re-open if questions remain.

**Comment by kleisauke** [comment]
[NetVips.Native v8.10.6](https://www.nuget.org/packages/NetVips.Native/8.10.6) is now available with prebuilt binaries containing MozJPEG instead of libjpeg-turbo.

Note that libvips resets to libjpeg-turbo's `JCP_FASTEST` defaults so this can be considered a "no-op" unless MozJPEG features are explicitly set.
